# Form implementation generated from reading ui file 'edit.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 544)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_type = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_type.setGeometry(QtCore.QRect(110, 140, 161, 31))
        self.comboBox_type.setObjectName("comboBox_type")
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(110, 200, 161, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_director = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_director.setGeometry(QtCore.QRect(110, 260, 161, 31))
        self.lineEdit_director.setObjectName("lineEdit_director")
        self.lineEdit_inn = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_inn.setGeometry(QtCore.QRect(110, 310, 161, 31))
        self.lineEdit_inn.setObjectName("lineEdit_inn")
        self.lineEdit_rating = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_rating.setGeometry(QtCore.QRect(110, 360, 161, 31))
        self.lineEdit_rating.setObjectName("lineEdit_rating")
        self.lineEdit_discount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_discount.setGeometry(QtCore.QRect(110, 420, 161, 31))
        self.lineEdit_discount.setObjectName("lineEdit_discount")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 210, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 270, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 320, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 370, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 430, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.label_6.setObjectName("label_6")
        self.pushButton_save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(140, 500, 75, 24))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(140, 60, 101, 41))
        self.label_8.setObjectName("label_8")
        self.pushButton_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(30, 20, 75, 24))
        self.pushButton_back.setObjectName("pushButton_back")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.label_2.setText(_translate("MainWindow", "Директор"))
        self.label_3.setText(_translate("MainWindow", "ИНН"))
        self.label_4.setText(_translate("MainWindow", "Рейтинг"))
        self.label_5.setText(_translate("MainWindow", "Скидка"))
        self.label_6.setText(_translate("MainWindow", "Тип"))
        self.pushButton_save.setText(_translate("MainWindow", "Сохранить"))
        self.label_8.setText(_translate("MainWindow", "Редактирование"))
        self.pushButton_back.setText(_translate("MainWindow", "Назад"))
