# Form implementation generated from reading ui file 'partners.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 505)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 40, 541, 401))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(610, 40, 91, 31))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(610, 90, 91, 31))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_orders = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_orders.setGeometry(QtCore.QRect(614, 150, 91, 41))
        self.pushButton_orders.setObjectName("pushButton_orders")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_add.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_delete.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_orders.setText(_translate("MainWindow", "Заявки"))
